// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ErrorResponse = {
    /**
     * Human-readable error message.
     */
    error: string;
};

export type JobResponse = {
    /**
     * URL where candidates can apply for the job.
     */
    applyUrl: string;
    /**
     * Sanitized HTML description supplied by the job source.
     */
    descriptionHtml?: string | null;
    /**
     * Employment type, such as `full_time`, `part_time`, or `contract`.
     */
    employmentType?: string | null;
    /**
     * Stable jobs.surf job identifier.
     */
    id: string;
    locations: Array<LocationResponse>;
    publishedAt?: string | null;
    /**
     * Identifier of the source that supplied the job.
     */
    sourceId: string;
    title: string;
    /**
     * Workplace arrangement: `remote`, `hybrid`, or `on_site`.
     */
    workplace?: string | null;
};

export type JobsResponse = {
    jobs: Array<JobResponse>;
    /**
     * Cursor for the next page, or `null` when there are no more jobs.
     */
    nextCursor?: string | null;
};

export type LocationResponse = {
    name: string;
};

export type SourceResponse = {
    /**
     * Adapter used to synchronize this source.
     */
    adapter: string;
    /**
     * Stable source identifier.
     */
    id: string;
    /**
     * Organization represented by this source.
     */
    organization: string;
};

export type SourcesResponse = {
    sources: Array<SourceResponse>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthErrors = {
    /**
     * Database is unavailable
     */
    503: unknown;
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: string;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opaque cursor returned by the previous page.
         */
        cursor?: string;
        /**
         * Number of jobs to return.
         */
        limit?: number;
        /**
         * Full-text search across job titles and descriptions.
         */
        query?: string;
        /**
         * Whether to return only fully remote or only non-remote jobs.
         */
        remote?: boolean;
        /**
         * Exact source identifier to match.
         */
        source?: string;
    };
    url: '/v1/jobs';
};

export type ListJobsErrors = {
    /**
     * Invalid query parameters
     */
    400: ErrorResponse;
    /**
     * Failed to list jobs
     */
    500: ErrorResponse;
};

export type ListJobsError = ListJobsErrors[keyof ListJobsErrors];

export type ListJobsResponses = {
    /**
     * Open jobs
     */
    200: JobsResponse;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Positive decimal job identifier
         */
        id: string;
    };
    query?: never;
    url: '/v1/jobs/{id}';
};

export type GetJobErrors = {
    /**
     * Invalid job identifier
     */
    400: ErrorResponse;
    /**
     * Job not found
     */
    404: ErrorResponse;
    /**
     * Failed to get job
     */
    500: ErrorResponse;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Open job
     */
    200: JobResponse;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type ListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sources';
};

export type ListSourcesErrors = {
    /**
     * Failed to list sources
     */
    500: ErrorResponse;
};

export type ListSourcesError = ListSourcesErrors[keyof ListSourcesErrors];

export type ListSourcesResponses = {
    /**
     * Known job sources
     */
    200: SourcesResponse;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];
